name: Deploy to Railway (test)

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.12.1

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install serve
        run: npm install -g serve

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Install Railway
        run: npm install -g @railway/cli

      - name: Deploy
        run: railway up --service client-dashboard
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
